# Housing Price Predictor — Week 2 Project
**Author:** Debiprasad Samal

A complete linear regression project using scikit-learn.
- Compare SGDRegressor (Gradient Descent) vs LinearRegression (Normal Equation)
- Predict house prices based on size, bedrooms, floors, and age

## 1. Import Libraries
Import: numpy, matplotlib.pyplot, SGDRegressor, LinearRegression, StandardScaler

In [2]:
# YOUR CODE HERE: import numpy, matplotlib, SGDRegressor, LinearRegression, StandardScaler
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import SGDRegressor, LinearRegression
from sklearn.preprocessing import StandardScaler

## 2. Load the Data
Load `houses.txt` using `np.loadtxt()`. The file has 4 features + 1 target (last column).
- X_train = first 4 columns (size, bedrooms, floors, age)
- y_train = last column (price)

In [ ]:
# YOUR CODE HERE: load houses.txt, split into X_train and y_train
data = np.loadtxt("data/houses.txt", delimiter=',')
X_train = data[:, :4]
y_train = data[:, 4]

In [4]:
# YOUR CODE HERE: print X_train.shape, X_train[:5], y_train[:5]
# Also print min, max, mean for each feature column
print(f"X_train shape: {X_train.shape}")
print(f"/n X_train data: {X_train[:5]}")
print(f"/n y_train data: {y_train[:5]}")
print(f"/n mean value  X_train data: {np.mean(X_train, axis = 0) } Max value  X_train data: {np.max(X_train, axis = 0)}Min value  X_train data: {np.min(X_train, axis = 0)}")
print(f"/n mean value  y_train data: {np.mean(y_train) } Max value of  y_train data: {np.max(y_train) } Min value of  y_train data: {np.min(y_train) }")





X_train shape: (100, 4)
/n X_train data: [[9.520e+02 2.000e+00 1.000e+00 6.500e+01]
 [1.244e+03 3.000e+00 1.000e+00 6.400e+01]
 [1.947e+03 3.000e+00 2.000e+00 1.700e+01]
 [1.725e+03 3.000e+00 2.000e+00 4.200e+01]
 [1.959e+03 3.000e+00 2.000e+00 1.500e+01]]
/n y_train data: [271.5 300.  509.8 394.  540. ]
/n mean value  X_train data: [1.41371e+03 2.71000e+00 1.38000e+00 3.86500e+01] Max value  X_train data: [3.194e+03 4.000e+00 2.000e+00 1.070e+02]Min value  X_train data: [788.   0.   1.  12.]
/n mean value  y_train data: 362.23952 Max value of  y_train data: 718.2 Min value of  y_train data: 158.0


## 4. Normalize the Data (for SGDRegressor)
Use `StandardScaler` to z-score normalize X_train. Print peak-to-peak range before and after.

In [5]:
# YOUR CODE HERE: create StandardScaler, fit_transform X_train, print ptp ranges
scalar = StandardScaler()
X_tras = scalar.fit_transform(X_train)

print(f"P to P range between X_train {np.ptp(X_train,axis=0)}")
print(f"P to P range between X_tras {np.ptp(X_tras,axis=0)}")

P to P range between X_train [2.406e+03 4.000e+00 1.000e+00 9.500e+01]
P to P range between X_tras [5.83735704 6.12923357 2.06021411 3.68430905]


## 5. Method 1 — SGDRegressor (Gradient Descent)
Create SGDRegressor with max_iter=1000, fit on normalized data, print w and b

In [6]:
# YOUR CODE HERE: create SGDRegressor, fit, print coef_ and intercept_

sgdr = SGDRegressor(max_iter= 1000)
sgdr.fit(X_tras,y_train)
w_s = sgdr.coef_
b_s = sgdr.intercept_
print(sgdr) # untill you print sgdr you cant extract w and b value
print(f"number of iterations completed: {sgdr.n_iter_}, number of weight updates: {sgdr.t_}")
print(f"Model parameter for w is :{w_s}")
print(f"Model parameter for b is :{b_s}")

SGDRegressor()
number of iterations completed: 131, number of weight updates: 13101.0
Model parameter for w is :[110.2412095  -21.3010217  -32.4738367  -37.81457894]
Model parameter for b is :[362.23296417]


## 6. Method 2 — LinearRegression (Normal Equation)
Create LinearRegression, fit on RAW data (no normalization needed), print w and b

In [7]:
# YOUR CODE HERE: create LinearRegression, fit on X_train (raw), print coef_ and intercept_

Linear_reg = LinearRegression()
Linear_reg.fit(X_train, y_train)
w = Linear_reg.coef_
b = Linear_reg.intercept_
print(f"Model parameter for w is :{w}")
print(f"Model parameter for b is :{b}")

Model parameter for w is :[  0.26836643 -32.90362407 -67.28804158  -1.46516763]
Model parameter for b is :221.50226366888356


## 7. Compare Predictions
Get predictions from both models on training data. Print first 4 predictions vs actual targets.

In [13]:
# YOUR CODE HERE: predict with both models, compare with y_train
y_pred_sgd = sgdr.predict(X_tras)
y_pred_lin = Linear_reg.predict(X_train)
# Remember: SGDRegressor needs normalized input, LinearRegression uses raw input
print(f"Predicted values from SGDRegressor: {y_pred_sgd[:5]}")
print(f"Predicted values from LinearRegression: {y_pred_lin[:5]}")
print(f"Actual target values: {y_train[:5]}")

Predicted values from SGDRegressor: [248.6966079  295.62276268 485.673613   389.63339038 491.81624077]
Predicted values from LinearRegression: [248.65591798 295.58045873 485.81689524 389.61035726 491.96762765]
Actual target values: [271.5 300.  509.8 394.  540. ]


## 8. Predict New House
Predict the price of a house with:
- 1200 sqft, 3 bedrooms, 1 floor, 40 years old

Use BOTH models and compare.

In [ ]:
# YOUR CODE HERE: predict price of [1200, 3, 1, 40] using both models
new_house = np.array([1200,3,1,40]).reshape(1,-1)
# Hint: for SGDRegressor, normalize the new house using scaler.transform()
new_house_norm = scalar.transform(new_house)
sgd_price = sgdr.predict(new_house_norm)
print(f"SGDRegressor prediction: ${sgd_price[0]*1000:.2f}")


# For LinearRegression, use raw values directly
lr_price = Linear_reg.predict(new_house)
print(f"LinearRegression prediction: ${lr_price[0]*1000:.2f}")

NotFittedError: This StandardScaler instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

## 9. Visualize Results
Plot predictions vs targets for each feature (4 subplots)

In [ ]:
# YOUR CODE HERE: create 1x4 subplots
# scatter actual targets and predictions for each feature

## 10. Summary
Print a comparison table of both methods

In [ ]:
# YOUR CODE HERE: print a summary comparing SGDRegressor vs LinearRegression
# Include: w values, b values, prediction for new house, method used